version: '0.1'

services:
    postgres:
      image: postgres:14.4-alpine
      container_name: postgresDBContainer
      ports:
        - "5433:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    rabbitmq:
      container_name: "rabbitmq"
      image: rabbitmq:3-management-alpine
      ports:
        # AMQP protocol port
        - '5672:5672'
        # HTTP management UI
        - '15672:15672'
      volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/